language: generic
cache:
  # Cache the global cargo directory, but NOT the local `target` directory which
  # we cannot reuse anyway when the nightly changes (and it grows quite large
  # over time).
  directories:
    - /home/travis/.cargo

os:
- linux
dist: xenial

before_script:
# Compute the Rust version we use. We do not use "language: rust" to have more control here.
- |
  if [[ "$TRAVIS_EVENT_TYPE" == cron ]]; then
    RUST_TOOLCHAIN=nightly
  else
    RUST_TOOLCHAIN=$(cat rust-version)
  fi
# install Rust
- curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN"
- export PATH=$HOME/.cargo/bin:$PATH
- rustup component add rust-src miri
- rustc --version

script:
- ./travis.sh

notifications:
  email:
    on_success: never
    recipients:
      - post+travis@ralfj.de
      - travis-miri@oli-obk.de
branches:
  only:
  - master
